/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kb;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class eatingDisorder extends javax.swing.JFrame {
    boolean boolArr[];
    int points[];
    /**
     * Creates new form eatingDisorder
     */
    public eatingDisorder(boolean boolArr[], int points[]) {
        this.boolArr = boolArr;
        this.points = points;
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height / 2;
        int width = screenSize.width / 2;
        int fHeight = getSize().height/2;
        int fWidth = getSize().width/2;
        setLocation(width-fWidth, height-fHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pertanyaan1 = new javax.swing.ButtonGroup();
        pertanyaan2 = new javax.swing.ButtonGroup();
        pertanyaan3 = new javax.swing.ButtonGroup();
        pertanyaan4 = new javax.swing.ButtonGroup();
        pertanyaan5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r3p2 = new javax.swing.JRadioButton();
        r3p3 = new javax.swing.JRadioButton();
        r3p4 = new javax.swing.JRadioButton();
        r3p5 = new javax.swing.JRadioButton();
        r3p1 = new javax.swing.JRadioButton();
        r2p3 = new javax.swing.JRadioButton();
        r2p4 = new javax.swing.JRadioButton();
        r2p5 = new javax.swing.JRadioButton();
        r2p1 = new javax.swing.JRadioButton();
        r2p2 = new javax.swing.JRadioButton();
        r1p3 = new javax.swing.JRadioButton();
        r1p4 = new javax.swing.JRadioButton();
        r1p5 = new javax.swing.JRadioButton();
        r1p1 = new javax.swing.JRadioButton();
        r1p2 = new javax.swing.JRadioButton();
        r4p3 = new javax.swing.JRadioButton();
        r4p4 = new javax.swing.JRadioButton();
        r4p5 = new javax.swing.JRadioButton();
        r4p1 = new javax.swing.JRadioButton();
        r4p2 = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        r5p3 = new javax.swing.JRadioButton();
        r5p4 = new javax.swing.JRadioButton();
        r5p5 = new javax.swing.JRadioButton();
        r5p1 = new javax.swing.JRadioButton();
        r5p2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rekam Analisis Psikis Individu");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel1.setFont(new java.awt.Font("STXinwei", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAPI");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Apakah Anda sering mengalami perubahan berlebihan dalam pola makan ");

        jLabel3.setText("Apakah anda pernah merasa khawatir dan cemas terhadap berat badan");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setText("Apakah anda pernah merasa kehilangan kendali saat makan, bahkan saat ");
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Apakah anda pernah merasa kesulitan untuk fokus pada kegiatan karena ");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel6.setText("pikiran anda secara terus-menerus berpikiran tentang makanan, berat badan, ");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel7.setText("1.");

        jLabel8.setText("2.");
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel9.setText("3.");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel10.setText("4.");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        pertanyaan3.add(r3p2);
        r3p2.setText("Jarang");
        r3p2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r3p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3p2ActionPerformed(evt);
            }
        });

        pertanyaan3.add(r3p3);
        r3p3.setText("Kadang-kadang");
        r3p3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r3p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3p3ActionPerformed(evt);
            }
        });

        pertanyaan3.add(r3p4);
        r3p4.setText("Sering");
        r3p4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r3p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3p4ActionPerformed(evt);
            }
        });

        pertanyaan3.add(r3p5);
        r3p5.setText("Selalu");
        r3p5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r3p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3p5ActionPerformed(evt);
            }
        });

        pertanyaan3.add(r3p1);
        r3p1.setText("Tidak Pernah");
        r3p1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r3p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3p1ActionPerformed(evt);
            }
        });

        pertanyaan2.add(r2p3);
        r2p3.setText("Kadang-kadang");
        r2p3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r2p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2p3ActionPerformed(evt);
            }
        });

        pertanyaan2.add(r2p4);
        r2p4.setText("Sering");
        r2p4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r2p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2p4ActionPerformed(evt);
            }
        });

        pertanyaan2.add(r2p5);
        r2p5.setText("Selalu");
        r2p5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r2p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2p5ActionPerformed(evt);
            }
        });

        pertanyaan2.add(r2p1);
        r2p1.setText("Tidak Pernah");
        r2p1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r2p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2p1ActionPerformed(evt);
            }
        });

        pertanyaan2.add(r2p2);
        r2p2.setText("Jarang");
        r2p2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r2p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2p2ActionPerformed(evt);
            }
        });

        pertanyaan1.add(r1p3);
        r1p3.setText("Kadang-kadang");
        r1p3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r1p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1p3ActionPerformed(evt);
            }
        });

        pertanyaan1.add(r1p4);
        r1p4.setText("Sering");
        r1p4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r1p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1p4ActionPerformed(evt);
            }
        });

        pertanyaan1.add(r1p5);
        r1p5.setText("Selalu");
        r1p5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r1p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1p5ActionPerformed(evt);
            }
        });

        pertanyaan1.add(r1p1);
        r1p1.setText("Tidak Pernah");
        r1p1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r1p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1p1ActionPerformed(evt);
            }
        });

        pertanyaan1.add(r1p2);
        r1p2.setText("Jarang");
        r1p2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r1p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1p2ActionPerformed(evt);
            }
        });

        pertanyaan4.add(r4p3);
        r4p3.setText("Kadang-kadang");
        r4p3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r4p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4p3ActionPerformed(evt);
            }
        });

        pertanyaan4.add(r4p4);
        r4p4.setText("Sering");
        r4p4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r4p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4p4ActionPerformed(evt);
            }
        });

        pertanyaan4.add(r4p5);
        r4p5.setText("Selalu");
        r4p5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r4p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4p5ActionPerformed(evt);
            }
        });

        pertanyaan4.add(r4p1);
        r4p1.setText("Tidak Pernah");
        r4p1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r4p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4p1ActionPerformed(evt);
            }
        });

        pertanyaan4.add(r4p2);
        r4p2.setText("Jarang");
        r4p2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r4p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4p2ActionPerformed(evt);
            }
        });

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Anda, seperti makan berlebihan atau kurang makan, dalam beberapa minggu ");
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel12.setText("terakhir?");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel13.setText("dan penampilan fisik anda?");
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel14.setText("anda sedang tidak lapar? ");
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel15.setText("atau penampilan fisik?");
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel17.setText("Seberapa membatasi anda pada asupan makanan yang anda makan? ");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel18.setText("5.");
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        pertanyaan5.add(r5p3);
        r5p3.setText("Kadang-kadang");
        r5p3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r5p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5p3ActionPerformed(evt);
            }
        });

        pertanyaan5.add(r5p4);
        r5p4.setText("Membatasi");
        r5p4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r5p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5p4ActionPerformed(evt);
            }
        });

        pertanyaan5.add(r5p5);
        r5p5.setText("Selalu Membatasi");
        r5p5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r5p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5p5ActionPerformed(evt);
            }
        });

        pertanyaan5.add(r5p1);
        r5p1.setText("Tidak Membatasi");
        r5p1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r5p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5p1ActionPerformed(evt);
            }
        });

        pertanyaan5.add(r5p2);
        r5p2.setText("Jarang");
        r5p2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        r5p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5p2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(r1p2)
                                    .addComponent(r1p3)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(r1p5)
                                        .addComponent(r1p4))
                                    .addComponent(r1p1)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))))
                        .addGap(39, 39, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r3p2)
                                        .addComponent(r3p3)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(r3p5)
                                            .addComponent(r3p4))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r5p2)
                                            .addComponent(r5p3)
                                            .addComponent(r5p5)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r5p1)
                                            .addComponent(r5p4)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r4p2)
                                            .addComponent(r4p3)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(r4p5)
                                                .addComponent(r4p4))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r4p1)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(nextBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelBtn))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(r2p1)
                                    .addComponent(r2p2)
                                    .addComponent(r2p3)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(r2p5)
                                        .addComponent(r2p4))
                                    .addComponent(r3p1))))
                        .addGap(0, 38, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r1p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r1p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r1p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r1p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r1p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3p1)
                .addGap(4, 4, 4)
                .addComponent(r3p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4p1)
                .addGap(7, 7, 7)
                .addComponent(r4p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r5p1)
                .addGap(7, 7, 7)
                .addComponent(r5p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r5p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r5p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r5p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(cancelBtn))
                .addGap(9, 9, 9))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r3p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3p2ActionPerformed

    private void r3p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3p3ActionPerformed

    private void r3p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3p4ActionPerformed

    private void r3p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3p5ActionPerformed

    private void r3p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3p1ActionPerformed

    private void r2p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2p3ActionPerformed

    private void r2p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2p4ActionPerformed

    private void r2p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2p5ActionPerformed

    private void r2p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2p1ActionPerformed

    private void r2p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2p2ActionPerformed

    private void r1p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1p3ActionPerformed

    private void r1p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1p4ActionPerformed

    private void r1p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1p5ActionPerformed

    private void r1p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1p1ActionPerformed

    private void r1p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1p2ActionPerformed

    private void r4p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4p3ActionPerformed

    private void r4p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4p4ActionPerformed

    private void r4p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4p5ActionPerformed

    private void r4p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4p1ActionPerformed

    private void r4p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4p2ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        boolean p1 = (pertanyaan1.getSelection()!=null);
        boolean p2 = (pertanyaan2.getSelection()!=null);
        boolean p3 = (pertanyaan3.getSelection()!=null);
        boolean p4 = (pertanyaan4.getSelection()!=null);
        boolean p5 = (pertanyaan5.getSelection()!=null);
        
        if(!p1 || !p2 || !p3 || !p4 || !p5){
            JOptionPane.showMessageDialog(null,"Pertanyaannya harus terisi semua!","Error!",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int sum=0;
            if(r1p1.isSelected()){
                sum = sum + 1;
            } else if(r1p2.isSelected()){
                sum = sum + 2;
            } else if(r1p3.isSelected()){
                sum = sum + 3;
            } else if(r1p4.isSelected()){
                sum = sum + 4;
            } else if(r1p5.isSelected()){
                sum = sum + 5;
            }
            if(r2p1.isSelected()){
               sum = sum + 1;
            } else if(r2p2.isSelected()){
                sum = sum + 2;
            } else if(r2p3.isSelected()){
               sum = sum + 3;
            } else if(r2p4.isSelected()){
                sum = sum + 4;
            } else if(r2p5.isSelected()){
                sum = sum + 5;
            }
            if(r3p1.isSelected()){
                sum = sum + 1;
            } else if(r3p2.isSelected()){
                sum = sum + 2;
            } else if(r3p3.isSelected()){
                sum = sum + 3;
            } else if(r3p4.isSelected()){
                sum = sum + 4;
            } else if(r3p5.isSelected()){
                sum = sum + 5;
            }
            if(r4p1.isSelected()){
                sum = sum + 1;
            } else if(r4p2.isSelected()){
                sum = sum + 2;
            } else if(r4p3.isSelected()){
                sum = sum + 3;
            } else if(r4p4.isSelected()){
                sum = sum + 4;
            } else if(r4p5.isSelected()){
                sum = sum + 5;
            }
            if(r5p1.isSelected()){
                sum = sum + 1;
            } else if(r5p2.isSelected()){
                sum = sum + 2;
            } else if(r5p3.isSelected()){
                sum = sum + 3;
            } else if(r5p4.isSelected()){
                sum = sum + 4;
            } else if(r5p5.isSelected()){
                sum = sum + 5;
            }
            points[3] = sum;
            int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
            if(a==JOptionPane.YES_OPTION){
                if(boolArr[4]){
                    anxiety np = new anxiety(boolArr, points);
                    np.setVisible(true);
                    this.setVisible(false);
                } else if(boolArr[5]){
                    depression np = new depression(boolArr, points);
                    np.setVisible(true);
                    this.setVisible(false);
                } else {
                    hasil np = new hasil(boolArr, points);
                    np.setVisible(true);
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to cancel?");  
        if(a==JOptionPane.YES_OPTION){
            programRuleBased prb = new programRuleBased();
            prb.setVisible(true);
            this.setVisible(false);            
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void r5p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5p3ActionPerformed

    private void r5p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5p4ActionPerformed

    private void r5p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5p5ActionPerformed

    private void r5p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5p1ActionPerformed

    private void r5p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5p2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eatingDisorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eatingDisorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eatingDisorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eatingDisorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eatingDisorder(new boolean[]{false, false, false, false, false, false}, new int[]{0,0,0,0,0,0}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBtn;
    private javax.swing.ButtonGroup pertanyaan1;
    private javax.swing.ButtonGroup pertanyaan2;
    private javax.swing.ButtonGroup pertanyaan3;
    private javax.swing.ButtonGroup pertanyaan4;
    private javax.swing.ButtonGroup pertanyaan5;
    private javax.swing.JRadioButton r1p1;
    private javax.swing.JRadioButton r1p2;
    private javax.swing.JRadioButton r1p3;
    private javax.swing.JRadioButton r1p4;
    private javax.swing.JRadioButton r1p5;
    private javax.swing.JRadioButton r2p1;
    private javax.swing.JRadioButton r2p2;
    private javax.swing.JRadioButton r2p3;
    private javax.swing.JRadioButton r2p4;
    private javax.swing.JRadioButton r2p5;
    private javax.swing.JRadioButton r3p1;
    private javax.swing.JRadioButton r3p2;
    private javax.swing.JRadioButton r3p3;
    private javax.swing.JRadioButton r3p4;
    private javax.swing.JRadioButton r3p5;
    private javax.swing.JRadioButton r4p1;
    private javax.swing.JRadioButton r4p2;
    private javax.swing.JRadioButton r4p3;
    private javax.swing.JRadioButton r4p4;
    private javax.swing.JRadioButton r4p5;
    private javax.swing.JRadioButton r5p1;
    private javax.swing.JRadioButton r5p2;
    private javax.swing.JRadioButton r5p3;
    private javax.swing.JRadioButton r5p4;
    private javax.swing.JRadioButton r5p5;
    // End of variables declaration//GEN-END:variables
}
