/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kb;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ASUS
 */
public class hasil extends javax.swing.JFrame {
    boolean boolArr[];
    int points[];
    /**
     * Creates new form hasil
     */
    public hasil(boolean boolArr[], int points[]) {
        initComponents();
        this.boolArr = boolArr;
        this.points = points;
        isiText();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height / 2;
        int width = screenSize.width / 2;
        int fHeight = getSize().height/2;
        int fWidth = getSize().width/2;
        setLocation(width-fWidth, height-fHeight);
    }
    
    public void isiText(){
        if(!boolArr[0]){
            sdText.setText("Anda tidak mengisi pertanyaan Sleeping Disorder");
        } else if (boolArr[0]){
            if(points[0]<=8){
                sdText.setText("Anda kemungkinan KECIL mengidap Sleeping Disorder");
            } else if(points[0]>8 && points[0]<15){
                sdText.setText("Anda kemungkinan SEDANG mengidap Sleeping Disorder");
            } else if(points[0]>=15){
                sdText.setText("Anda kemungkinan BESAR mengidap Sleeping Disorder");
            }
        }
        
        if(!boolArr[1]){
            adhdText.setText("Anda tidak mengisi pertanyaan ADHD");
        } else if (boolArr[1]){
            if(points[1]<=8){
                adhdText.setText("Anda kemungkinan KECIL mengidap ADHD");
            } else if(points[1]>8 && points[1]<15){
                adhdText.setText("Anda kemungkinan SEDANG mengidap ADHD");
            } else if(points[1]>=15){
                adhdText.setText("Anda kemungkinan BESAR mengidap ADHD");
            }
        }
        
        if(!boolArr[2]){
            ptsdText.setText("Anda tidak mengisi pertanyaan PTSD");
        } else if (boolArr[2]){
            if(points[2]<=12){
                ptsdText.setText("Anda kemungkinan KECIL mengidap PTSD");
            } else if(points[2]>12 && points[2]<24){
                ptsdText.setText("Anda kemungkinan SEDANG mengidap PTSD");
            } else if(points[2]>=24){
                ptsdText.setText("Anda kemungkinan BESAR mengidap PTSD");
            }
        }
        
        if(!boolArr[3]){
            edText.setText("Anda tidak mengisi pertanyaan Eating Disorder");
        } else if (boolArr[3]){
            if(points[3]<=10){
                edText.setText("Anda kemungkinan KECIL mengidap Eating Disorder");
            } else if(points[3]>10 && points[3]<19){
                edText.setText("Anda kemungkinan SEDANG mengidap Eating Disorder");
            } else if(points[3]>=19){
                edText.setText("Anda kemungkinan BESAR mengidap Eating Disorder");
            }
        }
        
        if(!boolArr[4]){
            anxietyText.setText("Anda tidak mengisi pertanyaan Anxiety");
        } else if (boolArr[4]){
            if(points[4]<=10){
                anxietyText.setText("Anda kemungkinan KECIL mengidap Anxiety");
            } else if(points[4]>10 && points[4]<19){
                anxietyText.setText("Anda kemungkinan SEDANG mengidap Anxiety");
            } else if(points[4]>=19){
                anxietyText.setText("Anda kemungkinan BESAR mengidap Anxiety");
            }
        }
        if(!boolArr[5]){
            depressionText.setText("Anda tidak mengisi pertanyaan Depression");
        } else if (boolArr[5]){
            if(points[5]<=10){
                depressionText.setText("Anda kemungkinan KECIL mengidap Depression");
            } else if(points[5]>10 && points[5]<19){
                depressionText.setText("Anda kemungkinan SEDANG mengidap Depression");
            } else if(points[5]>=19){
                depressionText.setText("Anda kemungkinan BESAR mengidap Depression");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sdText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        adhdText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ptsdText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        edText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        anxietyText = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        depressionText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 611));

        jLabel1.setFont(new java.awt.Font("STXinwei", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAPI");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sdText.setEditable(false);

        jLabel20.setText("Sleeping Disorder");

        adhdText.setEditable(false);

        jLabel21.setText("ADHD");

        ptsdText.setEditable(false);

        jLabel22.setText("PTSD");

        edText.setEditable(false);

        jLabel23.setText("Eating Disorder");

        anxietyText.setEditable(false);

        jLabel24.setText("Anxiety");

        depressionText.setEditable(false);

        jLabel25.setText("Depression");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(sdText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(adhdText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(ptsdText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(edText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(anxietyText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(depressionText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adhdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptsdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anxietyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depressionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasil(new boolean[]{false, false, false, false, false, false}, new int[]{15,15,15,15,15,15}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhdText;
    private javax.swing.JTextField anxietyText;
    private javax.swing.JTextField depressionText;
    private javax.swing.JTextField edText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ptsdText;
    private javax.swing.JTextField sdText;
    // End of variables declaration//GEN-END:variables
}
